src/Presentation/FaraMedia.Web/Models/Polls/PollModel.cs
using System.Collections.Generic;
using Fara.Web.Framework.Mvc;

namespace Fara.Web.Models.Polls
{
    public class PollModel : BaseFaraEntityModel
    {
        public PollModel()
        {
            Answers = new List<PollAnswerModel>();
        }

        public string Name { get; set; }

        public bool AlreadyVoted { get; set; }

        public int TotalVotes { get; set; }
        
        public IList<PollAnswerModel> Answers { get; set; }
    }

    public class PollAnswerModel : BaseFaraEntityModel
    {
        public string Name { get; set; }

        public int NumberOfVotes { get; set; }

        public double PercentOfTotalVotes { get; set; }
    }
}

src/Presentation/FaraMedia.Web/Controllers/PollController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Fara.Core;
using Fara.Core.Domain.Polls;
using Fara.Services.Customers;
using Fara.Services.Localization;
using Fara.Services.Polls;
using Fara.Web.Models.Polls;

namespace Fara.Web.Controllers
{
    public class PollController : BaseFaraController
    {
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IPollService _pollService;
        private readonly IWebHelper _webHelper;

        public PollController(ILocalizationService localizationService,
            IWorkContext workContext, IPollService pollService,
            IWebHelper webHelper)
        {
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._pollService = pollService;
            this._webHelper = webHelper;
        }


        protected PollModel PreparePollModel(Poll poll)
        {
            var model = new PollModel()
            {
                Id = poll.Id,
                AlreadyVoted = poll.AlreadyVoted(_workContext.CurrentCustomer),
                Name = poll.Name
            };
            var answers = poll.PollAnswers.OrderBy(x => x.DisplayOrder);
            foreach (var answer in answers)
                model.TotalVotes += answer.NumberOfVotes;
            foreach (var pa in answers)
            {
                model.Answers.Add(new PollAnswerModel()
                {
                    Id = pa.Id,
                    Name = pa.Name,
                    NumberOfVotes = pa.NumberOfVotes,
                    PercentOfTotalVotes = model.TotalVotes > 0 ? ((Convert.ToDouble(pa.NumberOfVotes) / Convert.ToDouble(model.TotalVotes)) * Convert.ToDouble(100)) : 0,
                });
            }

            return model;
        }

        [ChildActionOnly]
        public ActionResult PollBlock(string systemKeyword)
        {
            Poll poll = _pollService.GetPollBySystemKeyword(systemKeyword);
            if (poll == null ||
                !poll.Published ||
                (poll.StartDateUtc.HasValue && poll.StartDateUtc.Value > DateTime.UtcNow) ||
                (poll.EndDateUtc.HasValue && poll.EndDateUtc.Value < DateTime.UtcNow))
                return Content(string.Empty);

            var model = PreparePollModel(poll);
            return PartialView(model);
        }
        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Vote(int pollAnswerId)
        {
            var pollAnswer = _pollService.GetPollAnswerById(pollAnswerId);
            if (pollAnswer == null)
                throw new ArgumentException("No poll answer found with the specified id");

            string result = "Thank you!";
            bool success = false;


            if (!_workContext.CurrentCustomer.IsRegistered())
            {
                result = _localizationService.GetResource("Polls.OnlyRegisteredUsersVote");
            }
            else
            {
                var poll = pollAnswer.Poll;

                bool alreadyVoted = poll.AlreadyVoted(_workContext.CurrentCustomer);
                if (!alreadyVoted)
                {
                    
                    pollAnswer.PollVotingRecords.Add(new PollVotingRecord()
                    {
                        PollAnswerId = pollAnswer.Id,
                        CustomerId = _workContext.CurrentCustomer.Id,
                        IpAddress = _webHelper.GetCurrentIpAddress(),
                        IsApproved = true,
                        CreatedOnUtc = DateTime.UtcNow,
                        UpdatedOnUtc = DateTime.UtcNow,
                    });
                    
                    pollAnswer.NumberOfVotes = pollAnswer.PollVotingRecords.Count;
                    _pollService.UpdatePoll(poll);

                    result = _localizationService.GetResource("Polls.Voted");
                    success = true;
                }
            }

            return Json(new
            {
                Success = success,
                Result = result,
            });
        }


        [ChildActionOnly]
        public ActionResult HomePagePolls()
        {
            var polls = _pollService.GetPolls(_workContext.WorkingLanguage.Id, true, 0, int.MaxValue);
            var model = polls.Select(x => PreparePollModel(x)).ToList();
            return PartialView(model);
        }

    }
}

src/Presentation/FaraMedia.Web/Views/Poll/HomePagePolls.cshtml
@model IList<PollModel>
@using Fara.Web.Framework;
@using Fara.Web.Models.Polls;
@if (Model.Count > 0)
{<div class="todays-poll-box">
    <div class="todays-poll-box-block">
        @foreach (var poll in Model)
        { 
            @Html.Partial("_Poll", poll)
        }
    </div>
    </div>
}

src/Presentation/FaraMedia.Web/Views/Poll/PollBlock.cshtml
@model PollModel
@using Fara.Web.Models.Polls;
<div class="block block-poll">
    <div class="title">
        @T("Polls.Title")
    </div>
    <div class="clear">
    </div>
    <div class="listbox">
        @Html.Partial("_Poll", Model)
    </div>
</div>

src/Presentation/FaraMedia.Web/Views/Poll/_Poll.cshtml
@model PollModel
@using Fara.Web.Framework;
@using Fara.Web.Models.Polls;
<div class="poll-item">
    <span class="poll-display-text">@Model.Name</span>
    @if (Model.AlreadyVoted)
    {
        <div class="poll-results">
            @foreach (var item in Model.Answers)
            {
                @string.Format(T("Polls.VotesResultLine").Text, item.Name, item.NumberOfVotes, item.PercentOfTotalVotes.ToString("0.0"))
                <br />
            }
            <span class="poll-total-votes">@string.Format(T("Polls.TotalVotes").Text, Model.TotalVotes)</span>
        </div>
    }
    else
    {
        <div id="pnl-poll-vote-@(Model.Id)" class="poll-take-poll">
            @foreach (var item in Model.Answers)
            {
                <input id="pollanswers-@(item.Id)" type="radio" name="pollanswers-@(Model.Id)" value="@item.Id" />
                <label for="pollanswers-@(item.Id)">@item.Name</label>
                <br />
            }
            <input type="submit" name="vote-poll-@(Model.Id)" value="@T("Polls.Vote")" id="vote-poll-@(Model.Id)" class="submitpollvotebutton" />
            <span id="poll-voting-progress-@(Model.Id)" style="display: none;">@T("Common.Wait...")
                <img src='@Url.Content("~/Content/Images/ajax_loader_small.gif")' alt="@T("Common.Wait...")" />
            </span>@*TODO add a new 'ajax_loader_small.gif' with transparent background*@
        </div>
        <div class="clear">
        </div>
        <div id="pnl-poll-vote-result-@(Model.Id)">
        </div>
        
        <script type="text/javascript">
        $(document).ready(function () {
            $('#vote-poll-@(Model.Id)').click(function () {
                var pollAnswerId = $("input:radio[name=pollanswers-@(Model.Id)]:checked").val();
                if(typeof pollAnswerId == 'undefined'){
                    alert('Please select an answer');
                }
                else {
                    var voteProgress = $("#poll-voting-progress-@(Model.Id)");
                    voteProgress.show();
                    $.ajax({
                        cache:false,
                        type: "POST",
                        url: "@(Url.Action("Vote", "Poll"))",
                        data: "pollAnswerId=" + pollAnswerId,
                        success: function (data) {
                            voteProgress.hide();
                            $("#pnl-poll-vote-result-@(Model.Id)").html(data.Result);
                             if (data.Success) {
                                $('#pnl-poll-vote-@(Model.Id)').hide();                            
                             }
                             else {
                                $('#pnl-poll-vote-result-@(Model.Id)').fadeIn("slow").delay(2000).fadeOut("slow");
                             }
                        },
                        error:function (xhr, ajaxOptions, thrownError){
                            alert('Failed to vote.');
                            voteProgress.hide();
                        }  
                    });
                }
                return false;
            });
        });
        </script>
    }
</div>